/**
 * RemoteClient — the V1-Lean Remote connection seam.
 *
 * dotden v1 does no Provider auth of its own: no OAuth, no GitHub App, no PAT
 * storage, no keychain writes. This client implements the pure-git floor from
 * ADR 0020: the user pastes an existing Remote URL, dotden verifies that the
 * user's normal git credentials can reach it with `git ls-remote`, then runs
 * `chezmoi init <url>` to clone/initialize the Den. The same git command and
 * process environment are used for preflight and init so SSH agents, Git
 * Credential Manager, 1Password SSH agent, Keychain, WSL bridges, and askpass
 * hooks keep working exactly as they do for the user's CLI.
 */
import { mkdir } from 'node:fs/promises'
import {
  CommandAbortedError,
  CommandFailedError,
  runCommand,
  type CommandResult,
} from './process.js'

/**
 * Minimal trace envelope required at the renderer↔main IPC boundary.
 *
 * The richer Operation trace / Wide event model lands in later PRD 3 slices;
 * issue 1-03 only requires that Remote calls already cross the boundary with a
 * trace-shaped envelope so issue 1-04 can compose it into end-to-end operation
 * tests without changing the RemoteClient public API.
 */
export interface TraceEnvelope {
  /** Correlation id generated by the caller (currently preload) for this user action. */
  readonly traceId: string
}

/**
 * Construction options for {@link RemoteClient}.
 *
 * The binary paths come from bundled-tool resolution in production. Tests may
 * inject {@link run} to assert the exact CLI calls without touching real Remotes
 * or credentials.
 */
export interface RemoteClientOptions {
  /** Path to the bundled chezmoi binary used for `execute-template` and `init`. */
  readonly chezmoiBin: string
  /** Fallback path to the bundled git binary when chezmoi has no configured `git.command`. */
  readonly gitBin: string
  /** Local chezmoi source-state directory where the Den is cloned/initialized. */
  readonly sourceDir: string
  /** Destination/home directory passed to chezmoi for credential-identical initialization. */
  readonly destinationDir: string
  /** Maximum time a credential preflight/init process may run before being killed. */
  readonly timeoutMs?: number
  /** Test seam for the low-level child-process runner; production uses {@link runCommand}. */
  readonly run?: typeof runCommand
}

/**
 * Sanitized, user-displayable diagnostics for a failed Remote preflight.
 *
 * This deliberately preserves useful debugging shape (Provider host, URL scheme,
 * exit code, sanitized stderr) while redacting tokens and avoiding any dotden
 * attempt to repair credentials. V1-Lean's answer to auth failures is guidance:
 * set up your git credentials for the Provider and try again.
 */
export interface RemoteDiagnostics {
  /** Provider host parsed from the pasted Remote URL, e.g. `github.com`. */
  readonly host: string
  /** URL scheme/protocol class, e.g. `https`, `ssh`, or `file` for local tests. */
  readonly scheme: string
  /** git/OS exit code when the process reached an exit; absent for spawn-level failures. */
  readonly exitCode?: number
  /** Stderr with obvious secrets redacted and length capped for safe UI/log display. */
  readonly stderr: string
  /** Provider-agnostic help text shown to the user. */
  readonly help: string
}

/**
 * Result of checking whether the user's git credentials can reach a Remote.
 *
 * Maps to: resolve chezmoi's effective `git.command`, then run
 * `<git.command> ls-remote <url>`. A failed check returns diagnostics instead
 * of throwing so onboarding can render the Credential-error state inline.
 */
export interface PreflightResult {
  /** True when `git ls-remote <url>` exited successfully. */
  readonly reachable: boolean
  /** The git command used for the check (chezmoi config if present, bundled git fallback otherwise). */
  readonly gitCommand: string
  /** Failure details; present only when {@link reachable} is false. */
  readonly diagnostics?: RemoteDiagnostics
}

/**
 * Result of connecting a Remote and initializing the local Den.
 *
 * Returned only after a successful preflight and `chezmoi init <url>`.
 */
export interface ConnectResult {
  /** The git command that passed preflight and therefore identifies the credential path used. */
  readonly gitCommand: string
  /** Local source-state directory initialized by chezmoi. */
  readonly sourceDir: string
}

/**
 * Thrown by {@link RemoteClient.connectExistingRemote} when preflight fails.
 *
 * Preflight itself returns an inline result for UI state machines; connect uses
 * an exception because callers asked for a committed side effect (`chezmoi init`)
 * and no partial connection should be represented as success.
 */
export class RemotePreflightError extends Error {
  /** Sanitized diagnostics suitable for UI display and local logs. */
  constructor(readonly diagnostics: RemoteDiagnostics) {
    super(diagnostics.help)
  }
}

/**
 * Provider-agnostic Remote connector for dotden's V1-Lean auth model.
 *
 * Public methods map directly to the underlying git/chezmoi primitives:
 * - {@link preflightRemote} → `<git.command> ls-remote <url>`
 * - {@link connectExistingRemote} → successful preflight, then `chezmoi init <url>`
 * - {@link latestRemoteSha} → `<git.command> ls-remote <url> refs/heads/<branch>`
 *
 * The class never writes credentials, never talks to a Provider API, and never
 * overrides the user's credential environment. Timeouts/cancellation are the
 * safety valve for hung credential prompts, not disabling askpass/SSH agents.
 */
export class RemoteClient {
  private readonly run: typeof runCommand
  private readonly timeoutMs: number

  /**
   * Create a RemoteClient bound to one environment's source/destination dirs.
   *
   * @param options Binary paths, chezmoi dirs, timeout, and optional test process runner.
   */
  constructor(private readonly options: RemoteClientOptions) {
    this.run = options.run ?? runCommand
    this.timeoutMs = options.timeoutMs ?? 30_000
  }

  /**
   * Verify that a pasted Remote URL is reachable with the user's existing git credentials.
   *
   * Maps to `<git.command> ls-remote <url>`, where `git.command` is resolved via
   * chezmoi first and falls back to dotden's bundled git. The process inherits
   * the parent environment unchanged: no `GIT_SSH_COMMAND`, `SSH_AUTH_SOCK`,
   * `HOME`, credential-helper, or askpass overrides are injected.
   *
   * @param url HTTPS, SSH, scp-like, or file Remote URL supplied by the user.
   * @param request IPC trace envelope plus optional cancellation signal.
   * @returns Reachability plus either the git command used or sanitized diagnostics.
   */
  async preflightRemote(
    url: string,
    request: { readonly _trace: TraceEnvelope; readonly signal?: AbortSignal },
  ): Promise<PreflightResult> {
    const gitCommand = await this.effectiveGitCommand(request.signal)
    try {
      await this.runGit(gitCommand, ['ls-remote', url], request.signal)
      return { reachable: true, gitCommand }
    } catch (error) {
      const diagnostics = diagnosticsFromError(url, error)
      return { reachable: false, gitCommand, diagnostics }
    }
  }

  /**
   * Initialize the local Den from an existing, user-owned Remote.
   *
   * Maps to `chezmoi init <url>` after {@link preflightRemote} succeeds. The
   * source and destination dirs are passed explicitly so the initialized Den is
   * isolated to dotden's environment-local source state while applying against
   * the real home/destination dir.
   *
   * @param url Remote URL already checked or about to be checked by preflight.
   * @param request IPC trace envelope plus optional cancellation signal.
   * @returns The initialized source-state dir and git command that passed preflight.
   * @throws RemotePreflightError when credentials/reachability fail before init.
   */
  async connectExistingRemote(
    url: string,
    request: { readonly _trace: TraceEnvelope; readonly signal?: AbortSignal },
  ): Promise<ConnectResult> {
    const preflight = await this.preflightRemote(url, request)
    if (!preflight.reachable) {
      if (!preflight.diagnostics) throw new Error('Remote preflight failed without diagnostics')
      throw new RemotePreflightError(preflight.diagnostics)
    }

    await mkdir(this.options.sourceDir, { recursive: true })
    await mkdir(this.options.destinationDir, { recursive: true })
    await this.run(
      this.options.chezmoiBin,
      [
        // Pin chezmoi's two trees: source state is the local Den clone, destination is the real home.
        '--source',
        this.options.sourceDir,
        '--destination',
        this.options.destinationDir,
        // No TTY and force keep the init path non-interactive; credential prompts still belong to git.
        '--no-tty',
        '--force',
        'init',
        url,
      ],
      {
        timeoutMs: this.timeoutMs,
        signal: request.signal,
      },
    )
    return { gitCommand: preflight.gitCommand, sourceDir: this.options.sourceDir }
  }

  /**
   * Read the latest commit SHA advertised by a Remote branch without fetching.
   *
   * Maps to `<git.command> ls-remote <url> refs/heads/<branch>`. This is the
   * cheap Provider-agnostic primitive the tray poller will use to decide whether
   * a fetch is worth doing; it never calls GitHub/GitLab/etc. APIs and never
   * clones the Remote.
   *
   * @param url Remote URL to inspect.
   * @param branch Branch name to inspect, defaulting to `main`.
   * @param request IPC trace envelope plus optional cancellation signal.
   * @returns The full 40-character SHA, or null if the branch has no advertised ref.
   */
  async latestRemoteSha(
    url: string,
    branch = 'main',
    request: { readonly _trace: TraceEnvelope; readonly signal?: AbortSignal },
  ): Promise<string | null> {
    const gitCommand = await this.effectiveGitCommand(request.signal)
    const result = await this.runGit(
      gitCommand,
      ['ls-remote', url, `refs/heads/${branch}`],
      request.signal,
    )
    const [sha] = result.stdout.trim().split(/\s+/)
    return isFullSha(sha) ? sha : null
  }

  /**
   * Resolve chezmoi's effective git command, falling back to dotden's bundled git.
   *
   * Maps to `chezmoi execute-template '{{ .chezmoi.config.git.command }}'`.
   * If the user has configured chezmoi to use a custom git wrapper, preflight
   * uses that exact command so credential identity matches `chezmoi init`.
   */
  private async effectiveGitCommand(signal?: AbortSignal): Promise<string> {
    try {
      const result = await this.run(
        this.options.chezmoiBin,
        ['--no-tty', 'execute-template', '{{ .chezmoi.config.git.command }}'],
        { timeoutMs: this.timeoutMs, signal },
      )
      const configured = result.stdout.trim()
      if (configured && configured !== '<no value>') return configured
    } catch {
      // A missing host chezmoi config is not fatal; the bundled git binary is dotden's v1 floor.
    }
    return this.options.gitBin
  }

  /** Run the resolved git command with timeout/cancel but without environment overrides. */
  private runGit(
    command: string,
    args: readonly string[],
    signal?: AbortSignal,
  ): Promise<CommandResult> {
    // Intentionally omit `env`: runCommand will inherit process.env unchanged, preserving credential hooks.
    return this.run(command, args, { timeoutMs: this.timeoutMs, signal })
  }
}

/** Convert process failures into safe, Provider-agnostic UI diagnostics. */
function diagnosticsFromError(url: string, error: unknown): RemoteDiagnostics {
  const location = parseRemoteLocation(url)
  if (error instanceof CommandFailedError) {
    return {
      ...location,
      exitCode: error.result.exitCode,
      stderr: sanitizeStderr(error.result.stderr),
      help: credentialHelp(location.host),
    }
  }
  if (error instanceof CommandAbortedError) {
    return {
      ...location,
      exitCode: error.result.exitCode,
      stderr: sanitizeStderr(error.result.stderr),
      help: `Timed out while checking ${location.host}. Set up your git credentials (SSH key or token) for ${location.host}, then try again.`,
    }
  }
  return { ...location, stderr: '', help: credentialHelp(location.host) }
}

/** Build the V1-Lean auth failure copy: guide the user; never ask for/stash a token. */
function credentialHelp(host: string): string {
  return `Set up your git credentials (SSH key or token) for ${host}, then try again. If this is a private repo and the Provider says “Repository not found”, your credentials may not have access.`
}

/**
 * Parse Provider host and scheme from both URL-form and scp-like git Remotes.
 *
 * Supports `https://github.com/org/repo.git`, `ssh://git@example/repo.git`, and
 * scp-like `git@github.com:org/repo.git`. If parsing fails, diagnostics still
 * return a generic host so UI copy remains actionable.
 */
function parseRemoteLocation(remoteUrl: string): {
  readonly host: string
  readonly scheme: string
} {
  try {
    const parsed = new URL(remoteUrl)
    return { host: parsed.hostname, scheme: parsed.protocol.replace(':', '') }
  } catch {
    const scpLike = /^(?:[^@]+@)?([^:]+):/.exec(remoteUrl)
    return { host: scpLike?.[1] ?? 'this Remote', scheme: remoteUrl.includes(':') ? 'ssh' : 'file' }
  }
}

/**
 * Redact obvious credential material from stderr before it crosses into UI/logs.
 *
 * This is intentionally conservative and paired with a length cap. It is not a
 * secret-scanner replacement; it prevents the common auth-token-in-error cases
 * while preserving enough context for support/debugging.
 */
function sanitizeStderr(stderr: string): string {
  return stderr
    .replaceAll(/https:\/\/[^\s:@]+:[^\s@]+@/g, 'https://<redacted>@')
    .replaceAll(/gh[pousr]_[A-Za-z0-9_]+/g, '<redacted-token>')
    .slice(0, 2_000)
}

/** True when `git ls-remote` returned a full object id rather than empty/malformed output. */
function isFullSha(value: string | undefined): value is string {
  return /^[0-9a-f]{40}$/i.test(value ?? '')
}
