/**
 * remote — IPC contract types shared by main + renderer (ADR 0030).
 * Moved out of foundation so the renderer speaks them without importing main.
 */

/**
 * Minimal trace envelope required at the renderer↔main IPC boundary.
 *
 * The richer Operation trace / Wide event model lands in later PRD 3 slices;
 * issue 1-03 only requires that Remote calls already cross the boundary with a
 * trace-shaped envelope so issue 1-04 can compose it into end-to-end operation
 * tests without changing the RemoteClient public API.
 */
export interface TraceEnvelope {
  /** Correlation id generated by the caller (currently preload) for this user action. */
  readonly traceId: string
}

/**
 * Result of checking whether the user's git credentials can reach a Remote.
 *
 * Maps to: resolve chezmoi's effective `git.command`, then run
 * `<git.command> ls-remote <url>`. A failed check returns diagnostics instead
 * of throwing so onboarding can render the Credential-error state inline.
 */
export interface PreflightResult {
  /** True when `git ls-remote <url>` exited successfully. */
  readonly reachable: boolean
  /** The git command used for the check (chezmoi config if present, bundled git fallback otherwise). */
  readonly gitCommand: string
  /** Failure details; present only when {@link reachable} is false. */
  readonly diagnostics?: RemoteDiagnostics
}

/**
 * Result of connecting a Remote and initializing the local Den.
 *
 * Returned only after a successful preflight and `chezmoi init <url>`.
 */
export interface ConnectResult {
  /** The git command that passed preflight and therefore identifies the credential path used. */
  readonly gitCommand: string
  /** Local source-state directory initialized by chezmoi. */
  readonly sourceDir: string
  /**
   * What dotden found after clone. This is the launch-flow truth: empty/benign repos continue
   * through first-run onboarding, existing dotden repos route to returning setup, and foreign
   * chezmoi repos are refused for v1.
   */
  readonly repositoryKind: 'greenfield' | 'dotden' | 'foreign-chezmoi'
}

/**
 * Sanitized, user-displayable diagnostics for a failed Remote preflight.
 *
 * This deliberately preserves useful debugging shape (Provider host, URL scheme,
 * exit code, sanitized stderr) while redacting tokens and avoiding any dotden
 * attempt to repair credentials. V1-Lean's answer to auth failures is guidance:
 * set up your git credentials for the Provider and try again.
 */
export interface RemoteDiagnostics {
  /** Provider host parsed from the pasted Remote URL, e.g. `github.com`. */
  readonly host: string
  /** URL scheme/protocol class, e.g. `https`, `ssh`, or `file` for local tests. */
  readonly scheme: string
  /** git/OS exit code when the process reached an exit; absent for spawn-level failures. */
  readonly exitCode?: number
  /** Stderr with obvious secrets redacted and length capped for safe UI/log display. */
  readonly stderr: string
  /** Provider-agnostic help text shown to the user. */
  readonly help: string
}
